{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform vec3 blob1;\nuniform vec3 blob2;\nuniform vec3 blob3;\nuniform vec3 color1;\nuniform vec3 color2;\nuniform vec3 color3;\nuniform vec3 backgroundColor;\n\nvec4 fragColor;\n\nvec3 FLT_flutter_local_draw_circle(vec2 position, vec3 color, float size)\n{\n    float circle = length(position);\n    circle = 1.0 - smoothstep(0.0, size, circle);\n    return color * circle;\n}\n\nvoid FLT_main()\n{\n    vec2 coord = flutter_FragCoord.xy / resolution;\n    vec3 canvas = vec3(0.0);\n    canvas += backgroundColor;\n    vec2 param = coord - (blob1.xy / resolution);\n    vec3 param_1 = color1;\n    float param_2 = blob1.z;\n    vec3 circle1 = FLT_flutter_local_draw_circle(param, param_1, param_2);\n    vec2 param_3 = coord - (blob2.xy / resolution);\n    vec3 param_4 = color2;\n    float param_5 = blob2.z;\n    vec3 circle2 = FLT_flutter_local_draw_circle(param_3, param_4, param_5);\n    vec2 param_6 = coord - (blob3.xy / resolution);\n    vec3 param_7 = color3;\n    float param_8 = blob3.z;\n    vec3 circle3 = FLT_flutter_local_draw_circle(param_6, param_7, param_8);\n    canvas += circle1;\n    canvas += circle2;\n    canvas += circle3;\n    fragColor = vec4(canvas, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "blob1",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "blob2",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 3,
      "name": "blob3",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 4,
      "name": "color1",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 5,
      "name": "color2",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 6,
      "name": "color3",
      "rows": 3,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 7,
      "name": "backgroundColor",
      "rows": 3,
      "type": 10
    }
  ]
}